### ISSUE TITLE
Which is the fastest learner?

### ISSUE THREAD

**Issue by ghost** [brendanator/atari-rl#1]
Hi,

wow this is really a great repository :+1: 

Which method do you recommend to try first? 

The optimality tightening paper makes some really impressive claims, about the speed that they learn. I was just wondering if you've managed to reproduce any of their results? I just saw a theano implementation by one of the authors [here](https://github.com/ShibiHe/Q-Optimality-Tightening)  

Thanks for your advice,

Aj

**Comment by brendanator** [comment]
Thanks Aj :)

Both Double-Q learning and Persistent Advantage Learning seem to work well so I would start with them along with the standard DQN algorithm

My first impression of optimality tightening is that it doesn't seem to give too much improvement, but I haven't tried it out on many games and it's quite possible that there's a bug somewhere. I haven't been trying to reproduce results so much as learn how all these algorithms work

Let me know if it works for you
