### ISSUE TITLE
Error local variable 'grads' referenced before assignment

### ISSUE THREAD

**Issue by ashimko** [brendanator/atari-rl#2]
Hello!
Can you help me resolve an error?

> (py35_rl_gpu) alexshim@AS-PC:~/py_packs/atari-rl$ python main.py --game BreakoutI tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
> I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcudnn.so.5. LD_LIBRARY_PATH: 
> I tensorflow/stream_executor/cuda/cuda_dnn.cc:3517] Unable to load cuDNN DSO
> I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
> I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
> I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
> /home/alexshim/py_packs/gym/gym/__init__.py:22: UserWarning: DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.
>   warnings.warn('DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.')
> 2018-05-21 17:05:30 MainThread: Creating network and training operations
> Traceback (most recent call last):
>   File "main.py", line 145, in <module>
>     tf.app.run()
>   File "/home/alexshim/anaconda3/envs/py35_rl_gpu/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "main.py", line 111, in main
>     trainer = Trainer(create_config())
>   File "/home/alexshim/py_packs/atari-rl/agents/training.py", line 16, in __init__
>     self.global_step, self.agents = factory.create_agents()
>   File "/home/alexshim/py_packs/atari-rl/networks/factory.py", line 57, in create_agents
>     global_step, train_ops = self.create_train_ops()
>   File "/home/alexshim/py_packs/atari-rl/networks/factory.py", line 104, in create_train_ops
>     for grad, var in grads:
> UnboundLocalError: local variable 'grads' referenced before assignment

I am trying to train gpu version.
I will be very grateful.

**Comment by brendanator** [comment]
The GPU branch is WIP and doesn't currently work as you have seen

Please use master
